# Welcome to Jekyll!
#

# Site settings
title: Nepsone
description: A novel approach in dermatology
owner: Nepsone ehf # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@nepsone.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nepsone.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/nepsone
  #github: https://github.com/nepsone
  #linkedin-square: https://linkedin.com/in/nepsone
  #facebook-official: https://facebook.com/nepsone
  #google-plus-square: https://plus.google.com/u/0/+nepsone
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
